INSERT INTO employees (employee_id, name, lastname, creat_At) VALUES(1,'Jesus','Santo Vivar','2019-01-02')
INSERT INTO employees (employee_id, name, lastname, creat_At) VALUES(2,'Sergio ','Ramon Valdez ','2018-01-02')
INSERT INTO employees (employee_id, name, lastname, creat_At) VALUES(3,'Arthur ','Melho Safado','2019-01-16')
INSERT INTO employees (employee_id, name, lastname, creat_At) VALUES(4,'Jesus','Santo','2017-04-02')
INSERT INTO employees (employee_id, name, lastname, creat_At) VALUES(5,'Douglas','Costa Weverton','2019-09-18')
INSERT INTO employees (employee_id, name, lastname, creat_At) VALUES(6,'Ramiro','Santana Vivar','2019-01-02')
INSERT INTO employees (employee_id, name, lastname, creat_At) VALUES(7,'Abranhan','Ramon Valdez ','2018-01-02')
INSERT INTO employees (employee_id, name, lastname, creat_At) VALUES(8,'Ricardo','Trobel Ruiz','2019-01-16')
INSERT INTO employees (employee_id, name, lastname, creat_At) VALUES(9,'Tremebundp','Smith john','2017-04-02')
INSERT INTO employees (employee_id, name, lastname, creat_At) VALUES(10,'Jonas','Saiomon Vlez','2019-09-18')
INSERT INTO employees (employee_id, name, lastname, creat_At) VALUES(11,'Junior','Silvao Bhur','2019-01-02')
INSERT INTO employees (employee_id, name, lastname, creat_At) VALUES(12,'Ronaldo ','Rivao Valdez ','2018-01-02')
INSERT INTO employees (employee_id, name, lastname, creat_At) VALUES(13,'Friviño','Becker Ruiz','2019-01-16')
INSERT INTO employees (employee_id, name, lastname, creat_At) VALUES(14,'Alison','Sousa','2017-04-02')
INSERT INTO employees (employee_id, name, lastname, creat_At) VALUES(15,'Dani ','Couthino ','2019-09-18')
INSERT INTO employees (employee_id, name, lastname, creat_At) VALUES(16,'Dani','Alvez Souasa','2019-01-02')
INSERT INTO employees (employee_id, name, lastname, creat_At) VALUES(17,'Christiano ','Galvez Yerk  ','2018-01-02')
INSERT INTO employees (employee_id, name, lastname, creat_At) VALUES(18,'Vinicius','Junior ','2019-01-16')
INSERT INTO employees (employee_id, name, lastname, creat_At) VALUES(19,'Bruno ','Enriquez Pinto','2017-04-01')
INSERT INTO employees (employee_id, name, lastname, creat_At) VALUES(20,'Marcos','Aoas Correa','2019-09-18')


INSERT INTO providers(provider_id,name,email,phone,ruc) VALUES(1,'RAMNA SAC', 'proveedor1@gmail.com', 987876534, 789876535267)
INSERT INTO providers(provider_id,name,email,phone,ruc) VALUES(2,'GRUPO SAC', 'proveedor2@gmail.com', 667876534, 239876535267)
INSERT INTO providers(provider_id,name,email,phone,ruc) VALUES(3,'ALKOFARMA SAC', 'proveedor3@gmail.com', 777876534, 345876535267)
INSERT INTO providers(provider_id,name,email,phone,ruc) VALUES(4,'RETAIL SAC', 'proveedor4@gmail.com', 887876534, 445876535267)
INSERT INTO providers(provider_id,name,email,phone,ruc) VALUES(5,'UNION SAC', 'proveedor5@gmail.com', 997876534, 569876535267)

INSERT INTO categories(category_id,name,description) VALUES(1,'belleza y bienestar','categoria especializada en el cuidado personal ')
INSERT INTO categories(category_id,name,description) VALUES(2,'farmacia y salud','categoria encargada de las pildoras y/o pastillas')
INSERT INTO categories(category_id,name,description) VALUES(3,'mama y bebe','categoria encargada de los productos relacionados a la maternidad')
INSERT INTO categories(category_id,name,description) VALUES(4,'vitaminas y suplementos','categoria encargada de todos los suplementos y vitaminas')
